import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/header/Header';
import { Quicksand } from 'next/font/google';

const mainFont = Quicksand({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'EatyList',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      type: 'image/x-icon',
      url: '/favicon.ico',
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mainFont.className} style={{ fontSize: '1.2rem' }}>
        <Header />
        {children}
      </body>
    </html>
  );
}
